### ISSUE TITLE
rosdep install --ignore-src won't ignore src

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#267]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1681#issuecomment-220694599

In above issue, it refers hydro testing, but this issue happens even on indigo (rosdep == 0.11.4)

@k-okada As the main committer with [rosdep-install.sh](https://github.com/jsk-ros-pkg/jsk_travis/blob/master/rosdep-install.sh), do you have any idea?

**Comment by k-okada** [comment]
fixed by https://github.com/jsk-ros-pkg/jsk_travis/pull/266 ??

**Comment by wkentaro** [comment]
Actually, it is not fixed. 
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1681#issuecomment-220694599

**Comment by wkentaro** [comment]
It is fixed after rebooting travis. Closing this at this time..
Thanks @k-okada .
